### ISSUE TITLE
Github Action does not Label PRs

### ISSUE THREAD

**Issue by ChrisOwen101** [JulienKode/team-labeler-action#88]
Hi, just wondering if this project is still supported as I'm struggling to get it to work

- Github Action: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/.github/workflows/team-labeler.yml
- Teams Config: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/.github/teams.yml
- Example Run: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/runs/2679581247?check_suite_focus=true

As you can see, I'd expect my PR to be tagged with the `Improvement` label.

Do you have any advice?

**Comment by ChrisOwen101** [comment]
@JulienKode

**Comment by JulienKode** [comment]
Thanks for submitting this issue,

Sorry that you have some issue with it 

Can you try the following version please ?

```
name: "team-labeller"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: JulienKode/team-labeler-action@v0.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
